# Generated by Django 5.1.1 on 2024-09-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=None)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False, help_text='default=0,Hidden=1')),
                ('trending', models.BooleanField(default=False, help_text='default=0,Hidden=1')),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=200)),
                ('meta_description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to=None)),
                ('small_description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default,1=trending')),
                ('tag', models.CharField(max_length=100)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=200)),
                ('meta_description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
