# Generated by Django 5.1.1 on 2024-09-25 11:38

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=store.models.get_file_path),
        ),
    ]
