# Generated by Django 5.1.1 on 2024-10-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_to_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_to_cart',
        ),
    ]
